### ISSUE TITLE
Write annotations for notebook 08 (paper replicating)

### ISSUE THREAD

**Issue by mrdbourke** [mrdbourke/pytorch-deep-learning#14]

**Comment by mrdbourke** [comment]
Going through the notebook here: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/08_pytorch_paper_replicating.ipynb 

## TODO

- [ ] Find a way to visualize the model architecture programmatically, [Netron?](https://netron.app/)or TensorBoard?
- [ ] Add docstrings to sections of notebook (docstrings help to explain the code)
- [ ] Go through the notebook and add annotations for each section
- [ ] Create images for each section
- [ ] Add extra resources for paper replicating
- [ ] Add resources for inspiration for creating the notebook 
- [ ] Add extensions for learning more about the Transformer architecture

**Comment by mrdbourke** [comment]
Done, notebook fully ready: https://www.learnpytorch.io/08_pytorch_paper_replicating/
